version: "3"

networks:
  app:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: kk-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    user: "0:0"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mysql:/var/lib/mysql

  front-end:
    build: ./front-end
    container_name: kk-front-end
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  back-end:
    build:
      context: ./back-end
    container_name: kk-back-end
    environment:
      # Avaliable value: default (or any value not specified below), dev, debug, prod.
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - mysql
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    user: "0:0"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.ssh/back-end.key:/root/.ssh/id_rsa:ro
      - ~/knowledge-king-back-end:/app

  code-server:
    image: linuxserver/code-server
    container_name: kk-code-server
    environment:
      - PUID=0
      - PGID=0
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - SUDO_PASSWORD=${CODE_SERVER_PASSWORD}
    ports:
      - ${CODE_SERVER_PORT}:8443
    restart: always
    stdin_open: true
    tty: true
    user: "0:0"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./.ssh/code-server.key:/root/.ssh/id_rsa
      - ./code-server/data:/config/data
      - ./code-server/extensions:/config/extensions
      - ~/knowledge-king-back-end:/config/workspace

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kk-phpmyadmin
    environment:
      - PMA_HOST=mysql
#      - PMA_USER=${MYSQL_USER}
#      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ABSOLUTE_URI=${PHPMYADMIN_ABSOLUTE_URI}
    depends_on:
      - mysql
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    image: nginx:latest
    container_name: kk-nginx
    ports:
      - 80:80
    depends_on:
      - front-end
      - back-end
      - phpmyadmin
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
